FROM debian:buster

RUN apt update -y \
    && apt upgrade -y
RUN apt install nginx -y
RUN apt install openssl -y
RUN mkdir -p /etc/nginx/ssl
RUN openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=IDF/L=Paris/O=42/OU=42/CN=tdameros.42.fr/UID=tdameros"

COPY nginx.conf /etc/nginx/nginx.conf

CMD ["nginx"]

EXPOSE 443